### ISSUE TITLE
ModuleNotFoundError: No module named flask_api

### ISSUE THREAD

**Issue by sterenas** [flask-api/flask-api#112]
Hi!
Wonder if you can shed some light. Installed flask-api on a Raspberry Pi 3 using:
sudo pip install Flask
sudo pip install Flask-API
No errors.  Tested a small python program.

from flask import request
from flask_api import FlaskAPI
....
Second line bombs with ModuleNotFoundError: No module name 'flask_api'
Sure I'm missing something obvious. Trying to follow this sample:
https://docs.dataplicity.com/docs/control-gpios-using-rest-api

Very much appreciate your comments. Thanks so much!

**Comment by shubhamranjan12** [comment]
Hi. Are you still facing this issue ?

**Comment by KowsalyaR97** [comment]
Hi everyone,
I faced the same issue; i did the following
pip install flask-api
>>> from flask_api import FlaskAPI

**Comment by shubhamranjan12** [comment]
> Hi everyone,
> I faced the same issue; i did the following
> pip install flask-api
> ![Screenshot_92](https://user-images.githubusercontent.com/58511867/76301237-f2deb000-62e3-11ea-8e44-570a855eadf8.png)

Hi ,
Locate flask api folder and check whether that path is there in your python path variable.

**Comment by KowsalyaR97** [comment]
Thanks for your reply, i solved the issue
