### ISSUE TITLE
Switching project away from custom domain name

### ISSUE THREAD

**Issue by tomchristie** [flask-api/flask-api#124]
Hi folks, I'm currently paying for the flaskapi.org domain, but since I've not been involved with this project for a long time I'm considering allowing the domain to expire.

I guess a sensible thing to do would be for this project to change the domain to a GitHub pages domain, rather than the custom domain name. It looks like @jacebrowning would be the person with permissions to change those settings right?

**Comment by jacebrowning** [comment]
@tomchristie Yeah, I can do that today or tomorrow.

**Comment by jacebrowning** [comment]
@tomchristie, you can cancel the domain renewal now.

**Comment by tomchristie** [comment]
Thanks Jace
