### ISSUE TITLE
Use with Blueprints.

### ISSUE THREAD

**Issue by TechStudent11** [flask-api/flask-api#128]
Hi there. I would like to use this module, however, I would use it with the `/api` endpoint, along with a bunch of other routes in a Blueprint. Is there a way I could use this in a Flask Blueprint?

**Comment by jacebrowning** [comment]
The `FlaskAPI` class should be a drop-in replacement for `Flask`, which will let your `/api` routes act as APIs while all other routes default to the normal Flask behavior.

**Comment by TechStudent11** [comment]
ohhhhhhh thanks!
