### ISSUE TITLE
DeprecationWarning: 'werkzeug.urls.url_decode_stream' is deprecated

### ISSUE THREAD

**Issue by CarstenKarbach** [flask-api/flask-api#159]
When using flask-api with the latest werkzeug version 2.3.7 I am getting this deprecation warning:
```
DeprecationWarning: 'werkzeug.urls.url_decode_stream' is deprecated and will be removed in Werkzeug 2.4. Use 'urllib.parse.parse_qs' instead.
```
Are you planning to replace this deprecated call?

You might need to do something like this:

```
def url_decode_stream(stream):
    import urllib
    body = stream.read()
    body_str = body.decode()
    return dict(urllib.parse.parse_qsl(body_str))
```

Thanks!

**Comment by codders** [comment]
Tried to address this with the code in #161 . Not sure about the backward-compatibility w.r.t Flask and Werkzeug

**Comment by codders** [comment]
@auvipy Now that #161 is merged, is there a plan to release a new version of the library to Pypi?
