### ISSUE TITLE
Allow formatting the docstring with markdown

### ISSUE THREAD

**Issue by rochacbruno** [flask-api/flask-api#21]
As in:

```
def my_api_resource():
    """":markdown
    # this is my resource documentation
   parameters:
   - bla bla bla
   - foo bar
  """
  return [{...}]
```

Create a template tag or filter to detect the presence of ":markdown" in the start of the **doc** to format in template using flask-mistune

**Comment by jacebrowning** [comment]
I think this might work now. Please reopen if not.

**Comment by iScripters** [comment]
Maybe I'm missing something, but I can't get markdown docstrings to work. Would using markdown in de docstring itself be enough or does it require an app setting or decorator?

I installed markdown-3.0.1, but the markdown in my docstring doesn't get parsed.

**Comment by jacebrowning** [comment]
Yeah, I saw something similar. I'll document that `markdown` 3+ is not supported.
