### ISSUE TITLE
Document how to customize the API theme

### ISSUE THREAD

**Issue by bestony** [flask-api/flask-api#45]
I want use a different Template To Show My API Interface.
How to set 
app.config?
Can you show all of this array named app.config?

**Comment by jacebrowning** [comment]
Is this available @tomchristie?

**Comment by tomchristie** [comment]
No documented API around that, no. Haven't looked at this project for long enough to be much help here.

**Comment by bogolla4** [comment]
@tomchristie @jacebrowning @bestony I came across this and used a workaround that works nicely.

- Create templates and static folders in your projects
- You might start by copying contents from Flask-API static and template folders
- Replace the stylesheets to your desired 
- Your can change the app name / logo from `/templates/base.html`
- Create a new blueprint and give the static  and template dirs
- Override `__init__()` function from FlaskAPI to register the new blueprint you created

*The snippet is shown below:*

```
from flask_api import FlaskAPI
from flask_api.app import urlize_quoted_links, APISettings

my-flask-api = Blueprint(
    'flask-api', __name__,
    url_prefix='/flask-api',
    template_folder='templates', static_folder='static'
)

class MyFlaskAPI(FlaskAPI):
    def __init__(self, *args, **kwargs):
        super(FlaskAPI, self).__init__(*args, **kwargs)
        self.api_settings = APISettings(self.config)
        self.register_blueprint(my_resources)
        self.jinja_env.filters['urlize_quoted_links'] = urlize_quoted_links
```

**Comment by jacebrowning** [comment]
I found a slightly simpler way to achieve the effect I wanted:

```
from flask import Blueprint
from flask_api import FlaskAPI

theme = Blueprint(
    'flask-api', __name__,
    url_prefix='/flask-api',
    template_folder='templates', static_folder='static'
)

app = FlaskAPI(__name__)
app.blueprints['flask-api'] = theme
```

**Comment by jacebrowning** [comment]
Would anyone like to make PR that adds this to the documentation?

**Comment by jessejohnson** [comment]
> Would anyone like to make PR that adds this to the documentation?

@jacebrowning I would love to -- as a first contribution :smiley:
