### ISSUE TITLE
Gui POST button not sending correct Content-Type header

### ISSUE THREAD

**Issue by Yuav** [flask-api/flask-api#46]
When browsing a CRUD interface, the POST (gui) action is sending Content-Type as a parameter: _content_type in addition to the payload, in addition to _content. This isn't working currently, and is never reaching the appropriate JSON endpoint causing 400 Bad Request to be returned.

Expected to see either:
1. Content-Type header set by Javascript at the frontend for the request
2. FlaskAPI parse the _content_type and _content params in the POST, and redirect to the appropriate target

**Comment by jacebrowning** [comment]
POST works for me. Please reopen if this is still an issue.
