### ISSUE TITLE
HTML form action misses prefix when using DispatcherMiddleware

### ISSUE THREAD

**Issue by ulope** [flask-api/flask-api#70]
When using DispatcherMiddleware to mount an API app under a path prefix the generated HTML forms  contain wrong paths in the form's `action` attribute.

The reason for that is that `request.full_path` is used in the template which [doesn't include the `script_root`](http://flask.pocoo.org/docs/0.12/api/#flask.Request.url). The easiest fix would probably be to just use `request.url`.

**Comment by rainulf** [comment]
See #90 !
