### ISSUE TITLE
Transfer this repository

### ISSUE THREAD

**Issue by jacebrowning** [flask-api/flask-api#76]
@tomchristie has [expressed interest](https://github.com/tomchristie/flask-api/pull/75#issuecomment-292074313) in transferring this repository to a new owner. While I'm happy to adopt it (as the primary maintainer right now), I thought I'd poll the audience.

😄 : transfer to @jacebrowning
🎉 : transfer to a new `flask-api` organization
❤️ : search for an existing organization with similar goals
😕 : none of these

**Comment by skaven81** [comment]
We are making use of FlaskAPI at Qualcomm and would like to see continued and active support for this package.  I think creating a `flask-api` organization is the right move, as that allows consistent reference to the project (the Github URL will stay the same, even as maintainers come and go).

**Comment by dutronlabs** [comment]
Sorry for being late to this thread. I'm all for either option 1 or 2. 
@jacebrowning My free time is clearing up a bit, so I'm happy to help maintain.

**Comment by jacebrowning** [comment]
@tomchristie I created https://github.com/flask-api. Want to transfer this repository there?
