### ISSUE TITLE
how to avoid redirect?

### ISSUE THREAD

**Issue by dcsan** [flask-api/flask-api#81]
I setup a basic route with a get URL
works from browser
but using curl i just get a redirect link

```
curl "http://localhost:5000/parse?sentence=stufff"
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>Redirecting...</title>
<h1>Redirecting...</h1>
<p>You should be redirected automatically to target URL: <a href="http://localhost:5000/parse/?sentence=stufff">http://localhost:5000/parse/?sentence=stufff</a>.  If not click the link.%                                                                                                                    
```

I tried also with 
`app.run(debug=False)`

but still getting this. Is there another switch somewhere that flips from the "browsable API" to something for production use?

**Comment by jacebrowning** [comment]
I'd recommend you read through the Flask documentation first. This project simply formats responses to make it easier to build and API. Most of the functionality is still provided by Flask:

- http://flask.pocoo.org/docs/0.12/quickstart/#routing
