### ISSUE TITLE
Project abandoned?

### ISSUE THREAD

**Issue by vinyll** [flask-api/flask-api#82]
It seems that latest updated are getting and older. Same for other branches.
Is the project fully abandoned with no v1.0 as planed?

**Comment by jacebrowning** [comment]
It's basically in maintenance mode. Most passing PRs are getting merged and released, but I don't personally need anything else from the roadmap in my projects.

For context, here are some related discussions:

-  https://github.com/flask-api/flask-api/issues/52
- https://github.com/flask-api/flask-api/issues/76

I could remove some bullet points from the roadmap to reflect the current nature of this project. I could also release v1.0 with the current contents?

What do you think?

**Comment by vinyll** [comment]
I do like the idea of having not adding extra features. Simple is better ❤️ 

Reading the tickets make me understand that more developments would be focused on https://github.com/tomchristie/apistar. I'm definitely giving it a try.

It may be interesting to update the readme here (and the website?) accordingly – clearing the mentions about some v1.0 – and eventually to mention about APIStar.

Or not?

**Comment by jacebrowning** [comment]
I don't know enough about API Star to recommend it, but it looks like a more full-fledged API framework than Flask-API intends to be.

I will update the docs to clarify that this project is just a simple drop-in replacement for Flask that makes API responses automatic.

**Comment by tomchristie** [comment]
FWIW having full Flask support for API Star is one of the things on the roadmap.

**Comment by vinyll** [comment]
I've been testing embedding apistar into [an existing Flask project](https://github.com/neomad-team/neomad.org).
I could do so using [api-star](http://zqpythonic.qiniucdn.com/data/20160415191842/index.html) (note the dash).

Not clear how different [api-star](https://pypi.python.org/pypi/api-star)  is from [apistar](https://pypi.python.org/pypi/apistar)?

(also note that the website 'api-star.org' mentioned on pypi is outdated)

**Comment by jacebrowning** [comment]
I have updated the README to accurately describe the state of this project.
