### ISSUE TITLE
No content responses should accept not only an empty string

### ISSUE THREAD

**Issue by jesuGMZ** [flask-api/flask-api#85]
Is confusing, specially when trying to keep consistence beetwen returned data types,  that to be able to send a 204 HTTP status code is needed to pass only an empty string not being valid and empty dictionary or None value for example.

Could be more flexible to support other "empty/no content" values.

**Comment by jacebrowning** [comment]
What happens now when you try to return an empty dictionary or `None`?

**Comment by jesuGMZ** [comment]
A couple of examples using version 1.0:

`return '', status.HTTP_204_NO_CONTENT` return status 204 and empty body

`return {}, status.HTTP_204_NO_CONTENT` return status 200 and body `{}`

`return [], status.HTTP_204_NO_CONTENT` return status 200 and body `[]`

`return None, status.HTTP_204_NO_CONTENT` return status 500 internal server error

**Comment by jacebrowning** [comment]
Thanks for the examples. Are you proposing that `None` should also return an empty body?

**Comment by jesuGMZ** [comment]
Thank to you for your time :)

My proposal is to allow `None` as well yes. I understand that an empty dictionary or list could violate the [RFC](https://tools.ietf.org/html/rfc7231#section-6.3.5)

> A 204 response is terminated by the first empty line after the header
> fields because it cannot contain a message body.

**Comment by jacebrowning** [comment]
I think we should be able patch in this behavior in one place in `flask_api/app.py`.

Feel free to send a PR with a test.

**Comment by jesuGMZ** [comment]
Consider it done, I will in the next days :+1:

**Comment by rainulf** [comment]
Please check out #88. Cheers!
