### ISSUE TITLE
Flask-API can't parse request longer the 64KB

### ISSUE THREAD

**Issue by lamehost** [flask-api/flask-api#86]
Flask-API multipart/form-data parser does not set buffer_size and hence relies on default value from werkzeug which is 64KB.

**Flask-API:**
https://github.com/flask-api/flask-api/blob/8dfff5db4722e898167784826d3a94b70a380c04/flask_api/parsers.py#L39

**Werkzeug**:
https://github.com/pallets/werkzeug/blob/8eb665a94aea9d9b56371663075818ca2546e152/werkzeug/formparser.py#L285

That is enough for most, but not all the applications.
I suggest to set buffer_size equal or larger to content_length.

**Comment by jacebrowning** [comment]
That seems reasonable to me. Would you like to create a PR for this?
